//
//  Comments.swift
//  Sentiments
//
//  Created by Shahin on 2018-11-10.
//  Copyright © 2018 98%Chimp. All rights reserved.
//

import Foundation

struct Comments
{
    static let comment0001 = "Chip, chip, chip ... that's the sound of Trump slowly destroying the Constitution piece by piece."
    static let comment0002 = "I think Whitaker is Acting attorney general, until a new, permanent one is chosen. Similar to Sally Yates as acting AG starting Jan 2017 until Lynch's successor was chosen (Sessions)."
    static let comment0003 = "First, it must be said this is just outrageous. Trump reportedly talked Anthony Kennedy into retiring. Then he shopped for a Supreme Court Justice who had about the most expansive view of presidential power to be found in the land. Meanwhile, Matthew Whitaker auditioned for Trump's DOJ by going on cable news shows and opining that Mueller's investigation should be curtailed, starved of funds if need be, and that the Special Counsel did not have the authority to look at the President or his family's finances. Wow! Too bad the President doesn't do this sort of strategic and tactical planning when it comes to public policy and governance. Anyway, Surely Meuller knew this was coming. That Trump's efforts to reel in the Special Counsel begin immediately after the midterm speaks of the urgency Trump felt to act. He is reportedly of the belief his son, Don, Jr., is about to be indicted. We have so far seen one half of this legal chess match. I have a feeling we are in very short order going to find out what steps Mueller took to inoculate his investigation. Can it be Trump out maneuvered Mueller . . . I find that very hard to believe. Regardless, it should not really have to come to that. Just how much obstruction of justice does Trump need to engage in before enough Repub Senators wake up and put country over party to put an end to this obscenity."
    static let comment0004 = "During law school, I studied under Justice Antonin Scalia.  He taught us the entire purpose of having a Constitution was \"to make sure nobody gets all the marbles.\"  Trump's only goal is to get all the marbles, just like his Russian idol Putin has done with his country."
    static let comment0005 = "Mr. Whitaker's apointment will only be unConstitutional if and when the President fails to nominate a new AG within a reasonable time. Until then the President has every right, indeed an obligation, to appoint an acting AG and nothing in law nor the Constitution demands that a temporary, acting AG have been confirmed by the Senate. That \"temporary, acting\" is what is important here. Meanwhile the authors can't point to a single Constitutional or legal requirement which supports their rather broad claim. They are of course entitled to their interpretations, to their opinions, but we all know the old saw about opinions. If in, say, eight months the President has failed to nominate a new AG then the authors will have a point. Maybe. Given, however, the fact that Republicans have a firm grip on the Senate it is very unlikely that President Trump will not appoint and the Senate will not confirm a new AG sometime shortly after the New Year when the new Senate is seated. I expect that the authors will then have even more, if equally facetous, objections to whomever the President nominates than they do to Mr. Whitaker. For now they are simply grasping at straws and, with respect, La Resistance simply grows more tendentious by the day. BTW word has Mueller now writing his report on the entire Russia charade so my bet is that this is all rather moot. Let's be honest, the authors' real concern is their fervid hope that Mueller brings down President Trump."
    static let comment0006 = "Ok, another mass shooting, and now a constitutional crisis.  It must be Thursday in America."
    static let comment0007 = "Isn't one of the authors of this OpEd, George Conway, Kellyanne Conway's husband? So challenging Trump's unconstitutional act so boldly and publicly in the NYTimes must make for interesting dinner conversation, at least."
    static let comment0008 = "This President can easily get \"advice and consent\" from this rubber stamp of a Senate, so it's just a matter of his asking for it, is it not?"
    static let comment0009 = "So who does Mueller or Rosenstein submit the report to, Whitaker? That would be a mistake."
    static let comment0010 = "Trump knows, with McConnell aboard the constitution doesn't matter."
    static let comment0011 = "The fact that President Trump immediately \"fired\" Jeff Sessions concomitant to Jeff Sessions submitting his resignation, and explicitly naming the \"replacement\" Attorney General signifies to me that the President is fearful of Mueller's report. Robert Mueller did state was ready but would NOT be released until a day after the election. What education in law tells me is that there is an intended collision between the reports release and appointment of a new attorney general. It is all bad. I do have to say that all of Trump's attorneys have been quiet and he has been quiet, for several weeks now, including those right before Mueller's announcement about his report and clearly the weeks after. Where is THAT report?"
    static let comment0012 = "You have a president who does not believe in the \"rule of law\", and pick and chooses, at will, from the Constitution, when it suits him. Also, to him, legalities, ethics and morals are an inconvenience. Under a normal, bi-partisan, Congress, Trump would have taken to task months ago. Thanks to GOP control of the Supreme Court, the House and Senate, Trump believes he can rule by fiat. He expects the Democrat led House to fall in line, as the GOP run House. Not doing so, he will take action. Whatever making \"war on the Democrats\" means. Thus, bringing up this, that Trump illegally appointed an Attorney General (temporary or permanent), with \"advice and consent\", is just part for Trump. Over the past 22 months, we have seen one common thread, anyone opposed to Trump has been fired or forced from office. Yesterday, was the latest. He  also gleefully read off a list of people who was glad to see gone from office. In a way, Trump will be ore dangerous, come January, than he is now. He already has his \"nationalist\" paramilitary performing more and more domestic terrorist acts. It would not be surprising that, in the not to distant future, that domestic terrorists goes too far. Trump will seize the opportunity to declare a true national emergency, ask fro broad powers  and suspend the Constitution. If by now people have not realized how dangerous Trump is; they will soon."
    static let comment0013 = "so is anyone going to do anything about this clear violation of the Constitution ???"
    static let comment0014 = "I am incredibly grateful for this article. I'd thought it was just me, lost in some internal Constitutional noise machine in my head, figuring my 40+ years practicing law had been wasted. Here's one way to look at this issue: Pretend a tragedy hit DC, wiping out everyone except for an Assistant AG on vacation in Tahiti. By order and line of succession, that person would become our President. That person would have been appointed, and the Senate would have given its advice and consent. We've not been given that option with Whitaker. He's got no more right to success than, no insult intended, your local postmaster. One cannot go outside the Senate to appoint a Presidential successor. Period."
    static let comment0015 = "Seriously? Presidents have been making recess appointments for centuries and they are constitutional.   Furthermore, the Senate, can, and probably will confirm Mr. Whitaker when it is back in session.  If it doesn't, the next senate, which will be even more republican, will.  Am I missing something here, or are the authors trying to create a tempest in a teapot?"
    static let comment0016 = "Katyal and Conway are correct.   The Whittaker appointment, given that it was made explicitly to permit the firing of the Attorney General, is indeed that of a principal officer.  As such it requires Senate approval. If Trump wishes to fight it out at the Supreme Court whether the undated resignation of Sessions, made at the president's request, was a required, open-ended resignation for the sole purpose of naming a new Attorney General, it wouldn't auger well for the president's other hotly-argued \"legal\" claims that up is really down."
    static let comments = [comment0001, comment0002, comment0003, comment0004, comment0005, comment0006, comment0007, comment0008, comment0009, comment0010, comment0011, comment0012, comment0013, comment0014, comment0015, comment0016]
}
